- name: Run server
  service:
    name: vpnserver
    state: started

- name: Configure server
  command: "{{ vpn_vpncmd }} {{ item }}"
  with_items:
    # enable L2TP over IPSec
    - "/cmd IPSecEnable /L2TP:yes /L2TPRaw:no /EtherIP:no /PSK:{{ vpn_ipsec_preshared_key }} /DefaultHub:{{ vpn_hub.name }}"
    # use safe cipher for encryption
    - "/cmd ServerCipherSet ECDHE-RSA-AES128-GCM-SHA256"
    # enable SecureNat mode
    - "/hub:{{ vpn_hub.name }} /cmd SecureNatEnable"

- name: Create groups
  command: "{{ vpn_vpncmd }} /hub:{{ vpn_hub.name }} /cmd GroupCreate {{ item }} /RealName:none /Note:none"
  with_items: "{{ vpn_groups }}"

- name: Create users
  command: "{{ vpn_vpncmd }} /hub:{{ vpn_hub.name }} /cmd UserCreate {{ item.name }} /group:{{ item.groups | first }} /RealName:none /Note:none"
  with_items: "{{ vpn_users }}"

- name: Set passwords
  command: "{{ vpn_vpncmd }} /hub:{{ vpn_hub.name }} /cmd UserPasswordSet {{ item.name }} /password:{{ item.password }}"
  with_items: "{{ vpn_users }}"

